-- ============================================================
-- جداول المنتجات والمتغيرات لـ Supabase
-- Products & Variants schema – اسم منتج، وصف، صورة، متغيرات (مقاس + لون + كمية)
-- ============================================================

-- 1) جدول التصنيفات (إن لم يكن موجوداً)
-- Categories: تصنيفات المنتجات
CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_ar TEXT NOT NULL,
  name_en TEXT NOT NULL,
  image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2) جدول المنتجات
-- Products: اسم المنتج، وصف، صورة، سعر، تصنيف
-- كل صف = منتج واحد (مثلاً: تيشيرت كلاسيك)
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
  name_ar TEXT NOT NULL,
  name_en TEXT NOT NULL,
  description_ar TEXT,
  description_en TEXT,
  image_url TEXT,
  price NUMERIC(12,2) NOT NULL DEFAULT 0,
  original_price NUMERIC(12,2),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3) جدول متغيرات المنتج
-- Product Variants: لكل منتج → مقاس + لون + كمية
-- مثال: نفس المنتج (تيشيرت) → أبيض مقاس 7 كمية 10، أبيض مقاس 8 كمية 20، أسود مقاس 7 كمية 5 ...
CREATE TABLE IF NOT EXISTS public.product_variants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  size TEXT NOT NULL,
  color TEXT NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 0,
  sku TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(product_id, size, color)
);

-- فهارس لتسريع الاستعلامات
CREATE INDEX IF NOT EXISTS idx_products_category_id ON public.products(category_id);
CREATE INDEX IF NOT EXISTS idx_product_variants_product_id ON public.product_variants(product_id);
CREATE INDEX IF NOT EXISTS idx_product_variants_stock ON public.product_variants(product_id, size, color) WHERE quantity > 0;

-- تعليق على الجداول
COMMENT ON TABLE public.products IS 'المنتجات: اسم، وصف، صورة، سعر';
COMMENT ON TABLE public.product_variants IS 'متغيرات المنتج: كل صف = مقاس + لون + كمية (مثلاً: أبيض 7 = 10، أبيض 8 = 20)';

-- ============================================================
-- RLS (اختياري) – نفّذه من لوحة Supabase إذا احتجت
-- ============================================================
-- ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.product_variants ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Allow public read categories" ON public.categories FOR SELECT USING (true);
-- CREATE POLICY "Allow public read products" ON public.products FOR SELECT USING (true);
-- CREATE POLICY "Allow public read product_variants" ON public.product_variants FOR SELECT USING (true);

-- ============================================================
-- أمثلة إدراج (للتجربة)
-- ============================================================

-- تصنيف
-- INSERT INTO public.categories (name_ar, name_en, image_url) VALUES
--   ('تيشيرتات', 'T-Shirts', 'https://example.com/cat1.jpg');

-- منتج
-- INSERT INTO public.products (category_id, name_ar, name_en, description_ar, description_en, image_url, price, original_price) VALUES
--   (1, 'تيشيرت كلاسيك أبيض', 'Classic White Tee', 'وصف بالعربي', 'Description in English', 'https://example.com/product1.jpg', 2500, 3000);

-- متغيرات: نفس المنتج، مقاسات وألوان وكميات مختلفة
-- INSERT INTO public.product_variants (product_id, size, color, quantity) VALUES
--   (1, '7', 'أبيض', 10),
--   (1, '8', 'أبيض', 20),
--   (1, '7', 'أسود', 5),
--   (1, '8', 'أسود', 15);
